live:
  password: INSERT-PRIVATE-APP-PASSWORD
  theme_id: "167506060"
  store: gossamer-gear.myshopify.com
  ignore_files:
  - config.example.yml
development:
  password: INSERT-PRIVATE-APP-PASSWORD
  theme_id: "167506060"
  store: gossamer-gear.myshopify.com
  ignore_files:
  - config.example.yml  
